# Generated by Django 3.1.3 on 2021-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeLeaveCategoryMapID', models.UUIDField(editable=False, unique=True)),
                ('EmployeeId', models.UUIDField(editable=False, unique=True)),
                ('LeaveCategoryId', models.UUIDField(editable=False, unique=True)),
                ('StartDate', models.DateTimeField(null=True)),
                ('EndDate', models.DateTimeField(null=True)),
                ('IsFirstHalfDay', models.BooleanField(default=False)),
                ('IsLastHalfDay', models.BooleanField(default=False)),
                ('Reason', models.CharField(max_length=1000)),
                ('Comments', models.CharField(max_length=1000)),
                ('ApplyDate', models.DateTimeField(auto_now_add=True)),
                ('ApprovedBy', models.CharField(max_length=1500)),
                ('ApproveDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.UUIDField(editable=False, unique=True)),
                ('ModifiedBy', models.UUIDField(editable=False, unique=True)),
                ('ModifiedDate', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('IsApprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employeep',
            name='department',
            field=models.CharField(choices=[('COMPANY', 'COMPANY'), ('FINANCE', 'FINANCE'), ('EMPLOYEE', 'EMPLOYEE')], max_length=20),
        ),
    ]
