# Generated by Django 3.1.3 on 2021-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210325_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavecategory',
            name='IsFirstHalfDay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeleavecategory',
            name='IsLastHalfDay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
