# Generated by Django 3.1.5 on 2021-03-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0006_auto_20210206_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_hr',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_manager',
            new_name='is_finance',
        ),
    ]
